version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - ../testground/pdf-files:/pdf-store/storage/pdf-files
    depends_on:
      - mongodb
  mongodb:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../testground/mongodb-data:/bitnami/mongodb