version: "3"
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./pdf-storage:/pdf-store/storage/pdf-files
    depends_on:
      - mongodb
  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
volumes:
  mongodb-data:
  pdf-storage: 
