# run: docker-compose up
version: "3"
services:
  webapp:
    build:
      context: ../pdf-store/
      dockerfile: ../pdf-store/Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - ./pdf-files:/pdf-store/storage/pdf-files
    depends_on:
      - mongodb
  mongodb:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/bitnami/mongodb